QA-135 Add tests for adcm_XX fixtures with xdist
arenadata/adcm_pytest_plugin pull request #34
Opened 2021-06-18 08:50 UTC by madlabman

2021-06-18 13:05 UTC, dgusakov requested changes
We need to add installation of the xdist, and presumably other dependencies in the future, to CI pipeline. It seems that the easiest way is to create a requirements.txt file in the tests folder and add `pip install -r tests/requirements.txt` to CI pipeline.

Pls refer to https://github.com/arenadata/ci/blob/d285d2713275b2678aefed2ac83a59e754c676a6/jjb/prs-and-per-push.yaml.conf#L2836-L2838 to add CI step

2021-06-28 09:38 UTC, dgusakov commented
bender build

2021-06-28 11:00 UTC, dgusakov approved these changes

2021-06-28 11:03 UTC, vgorkavenko approved these changes

2021-06-28 11:04 UTC, merged