Implement expectparam decorator
arenadata/adcm_pytest_plugin pull request #47
Opened 2021-07-15 09:23 UTC by madlabman

In some cases we rely on a fixture param. Introduced decorator applies `request.param` type checking.

2021-07-15 09:25 UTC, dgusakov requested changes

2021-07-15 09:25 UTC, dgusakov commented on src/adcm_pytest_plugin/utils.py
> +    ValueError: Expecting <class 'str'> instance as a fixture param
Add test with no param at all

2021-07-15 11:55 UTC, madlabman commented on src/adcm_pytest_plugin/utils.py
> +    ValueError: Expecting <class 'str'> instance as a fixture param
Done

2021-07-15 12:26 UTC, vgorkavenko submitted a review, later dismissed

2021-07-16 04:42 UTC, dgusakov approved these changes

2021-07-16 04:42 UTC, vgorkavenko approved these changes

2021-07-16 05:35 UTC, merged