Add isort pre-commit hook
arenadata/adcm_pytest_plugin pull request #75
Opened 2021-11-02 18:35 UTC by madlabman

2021-11-03 04:53 UTC, skhomuti approved these changes

2021-11-08 05:19 UTC, dgusakov requested changes
Also create commit with the initial imports alignment

2021-11-10 08:40 UTC, dgusakov commented
@madlabman bump version

2021-11-10 08:42 UTC, madlabman commented
> @madlabman bump version

@dgusakov, done.

2021-11-10 08:42 UTC, dgusakov approved these changes

2021-11-10 08:47 UTC, vgorkavenko approved these changes

2021-11-10 08:51 UTC, merged